accounts/urls.py
from django.urls import path

from .views import (
    profile,
    ProfileUpdateView,
    SignedDataPrivacyCreateView,
    DisclaimerCreateView,
    DisclaimerUpdateView,
    DisclaimerContactUpdateView,
)

app_name = "accounts"


urlpatterns = [
    path("profile/", profile, name="profile"),
    path("update/", ProfileUpdateView.as_view(), name="update_profile"),
    path(
        "data-privacy-review/",
        SignedDataPrivacyCreateView.as_view(),
        name="data_privacy_review",
    ),
    path(
        "disclaimer/<int:user_id>/update",
        DisclaimerUpdateView.as_view(),
        name="disclaimer_form_update",
    ),
    path(
        "disclaimer/<int:user_id>/",
        DisclaimerCreateView.as_view(),
        name="disclaimer_form",
    ),
    path(
        "emergency-contact/<int:user_id>/update/",
        DisclaimerContactUpdateView.as_view(),
        name="update_emergency_contact",
    ),
    path("", profile),
]

booking/urls.py
from django.urls import path
from django.views.generic import RedirectView


from booking.views import (
    RegularClassesEventListView,
    WorkshopEventListView,
    EventDetailView,
    PrivateClassesEventListView,
    BookingListView,
    BookingHistoryListView,
    toggle_waiting_list,
    shopping_basket_view,
    guest_shopping_basket,
    stripe_checkout,
    ajax_cart_item_delete,
    check_total,
    ajax_add_membership_to_basket,
    membership_purchase_view,
    MembershipListView,
    MembershipDetailView,
    GiftVoucherUpdateView,
    GiftVoucherPurchaseView,
    GiftVoucherDetailView,
    voucher_details,
    toggle_booking,
)
from booking.views.user_invoices_views import UserInvoiceListView


app_name = "booking"


urlpatterns = [
    path("my-bookings/", BookingListView.as_view(), name="bookings"),
    path("my-memberships/", MembershipListView.as_view(), name="user_memberships"),
    path(
        "membership-detail/<int:pk>/",
        MembershipDetailView.as_view(),
        name="membership_detail",
    ),
    path("booking-history/", BookingHistoryListView.as_view(), name="booking_history"),
    path(
        "classes/", RegularClassesEventListView.as_view(), name="regular_session_list"
    ),
    path("privates/", PrivateClassesEventListView.as_view(), name="private_list"),
    path("workshops/", WorkshopEventListView.as_view(), name="workshop_list"),
    path("event/<slug:slug>/", EventDetailView.as_view(), name="event_detail"),
    path("toggle-booking/<int:event_id>/", toggle_booking, name="toggle_booking"),
    path(
        "toggle-waiting-list/<int:event_id>/",
        toggle_waiting_list,
        name="toggle_waiting_list",
    ),
    # GIFT VOUCHERS
    path("gift-vouchers/", GiftVoucherPurchaseView.as_view(), name="buy_gift_voucher"),
    path(
        "gift-vouchers/<slug:slug>/update",
        GiftVoucherUpdateView.as_view(),
        name="gift_voucher_update",
    ),
    path(
        "gift-vouchers/<slug:slug>",
        GiftVoucherDetailView.as_view(),
        name="gift_voucher_details",
    ),
    path("voucher/<str:voucher_code>", voucher_details, name="voucher_details"),
    # MEMBERSHIPS
    path("memberships/", membership_purchase_view, name="membership_purchase"),
    path(
        "ajax-membership-purchase/",
        ajax_add_membership_to_basket,
        name="ajax_add_membership_to_basket",
    ),
    # SHOPPING BASKET
    path("shopping-basket/", shopping_basket_view, name="shopping_basket"),
    path("stripe-checkout/", stripe_checkout, name="stripe_checkout"),
    path("ajax-cart-item-delete/", ajax_cart_item_delete, name="ajax_cart_item_delete"),
    path("check-total/", check_total, name="check_total"),
    path("guest-shopping-basket/", guest_shopping_basket, name="guest_shopping_basket"),
    # transactions
    path("payment-history/", UserInvoiceListView.as_view(), name="transactions"),
    path("", RedirectView.as_view(url="/classes/", permanent=True)),
]

studioadmin/urls.py
from django.views.generic import RedirectView
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from .views.fees import (
    outstanding_fees_user,
    outstanding_fees_list,
    ajax_toggle_cancellation_fee_payment,
    ajax_toggle_remove_cancellation_fee,
    ajax_get_cancellation_fee_payment_status,
    ajax_get_user_total_fees,
)
from .views.register import (
    EventRegisterListView,
    register_view,
    booking_register_add_view,
    ajax_toggle_attended,
)
from .views.users import UserListView, UserDisclaimerView
from .views.waiting_list import event_waiting_list_view

app_name = "studioadmin"


urlpatterns = [
    path(
        "registers/classes/",
        staff_member_required(EventRegisterListView.as_view()),
        {"event_type": "regular_session"},
        name="regular_session_register_list",
    ),
    path(
        "registers/workshops/",
        staff_member_required(EventRegisterListView.as_view()),
        {"event_type": "workshop"},
        name="workshop_register_list",
    ),
    path(
        "registers/privates/",
        staff_member_required(EventRegisterListView.as_view()),
        {"event_type": "private"},
        name="private_register_list",
    ),
    path("registers/<slug:event_slug>/", register_view, name="event_register"),
    path(
        "registers/add-booking/<int:event_id>/",
        booking_register_add_view,
        name="bookingregisteradd",
    ),
    path(
        "registers/<int:booking_id>/toggle_attended/",
        ajax_toggle_attended,
        name="ajax_toggle_attended",
    ),
    path(
        "waiting-list/<slug:event_slug>/",
        event_waiting_list_view,
        name="event_waiting_list",
    ),
    path("students/", staff_member_required(UserListView.as_view()), name="user_list"),
    path(
        "student/<int:pk>/disclaimer/",
        staff_member_required(UserDisclaimerView.as_view()),
        name="user_disclaimer",
    ),
    path("fees/<int:user_id>/", outstanding_fees_user, name="user_fees"),
    path(
        "fees/ajax-toggle-cancellation-fee-payment/<int:booking_id>/",
        ajax_toggle_cancellation_fee_payment,
        name="ajax_toggle_cancellation_fee_payment",
    ),
    path(
        "fees/ajax-toggle-remove-cancellation-fee/<int:booking_id>/",
        ajax_toggle_remove_cancellation_fee,
        name="ajax_toggle_remove_cancellation_fee",
    ),
    path(
        "fees/ajax-cancellation-fee-payment-status/<int:booking_id>/",
        ajax_get_cancellation_fee_payment_status,
        name="ajax_get_cancellation_fee_payment_status",
    ),
    path(
        "fees/ajax-user-total-fees/<int:user_id>/",
        ajax_get_user_total_fees,
        name="ajax_get_user_total_fees",
    ),
    path("fees/", outstanding_fees_list, name="outstanding_fees"),
    path(
        "",
        RedirectView.as_view(
            url="/instructor-admin/registers/classes/", permanent=True
        ),
    ),
]

sunshine/urls.py
from django.urls import include, path, re_path

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import (
    CustomLoginView,
    CustomSignUpView,
    data_privacy_policy,
    cookie_policy,
)
from booking.views import permission_denied
from studioadmin.views.views import redirect_to_admin

urlpatterns = [
    path("", include("website.urls")),
    path("accounts/signup/", CustomSignUpView.as_view(), name="account_signup"),
    path("accounts/login/", CustomLoginView.as_view(), name="account_login"),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("data-privacy-policy/", data_privacy_policy, name="data_privacy_policy"),
    path("cookie-policy/", cookie_policy, name="cookie_policy"),
    re_path(r"^pf_admin.*", redirect_to_admin, name="redirect_old_link"),
    path("instructor-admin/", include("studioadmin.urls")),
    path("site-admin/", admin.site.urls),
    path("booking/", include("booking.urls")),
    path("timetable/", include("timetable.urls")),
    path("payments/", include("stripe_payments.urls")),
    path("not-available/", permission_denied, name="permission_denied"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:  # pragma: no cover
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

admin.autodiscover()
admin.site.site_header = "Sunshine Fitness"
admin.site.enable_nav_sidebar = False

timetable/urls.py
from django.urls import path

from timetable.views import TimetableListView


app_name = "timetable"


urlpatterns = [
    path("", TimetableListView.as_view(), name="timetable"),
]

website/urls.py
from django.conf import settings
from django.urls import path

from website.views import home, home_legacy, contact, faq, session_types, venues

app_name = "website"

urlpatterns = [
    path("contact/", contact, name="contact"),
    path("faq/", faq, name="faq"),
    path("what-we-offer/", session_types, name="session_types"),
    path("venues/", venues, name="venues"),
]

if settings.LEGACY_HOMEPAGE:
    urlpatterns.insert(0, path("", home_legacy, name="home"))
else:  # pragma: no cover
    urlpatterns.insert(0, path("", home, name="home"))

booking/views/booking_helpers.py
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import get_template

from activitylog.models import ActivityLog
from booking.email_helpers import email_waiting_lists
from booking.utils import host_from_request
from stripe_payments.utils import process_refund


def cancel_booking_from_view(request, booking):
    # 1) check if the booking can be cancelled
    # 2) check if it can be cancelled b/c it's membership booked within 15 mins
    # 3) Was it paid? - Yes
    #    a) Do we need to refund it?
    #    b) Do we need to put it back on a membership?
    # 4) Was it paid? - No
    # 5) Set it to cancelled/no-show/unpaid
    # 6) Email user (if previoulsy paid)
    # 7) Email waiting list users if required

    event = booking.event
    delete_from_shopping_basket = request.GET.get("ref") == "basket"

    # Booking can be fully cancelled if the event allows cancellation AND
    # the cancellation period is not past
    # If not, we let people cancel but leave the booking status OPEN and
    # set to no-show
    can_cancel_and_refund = booking.event.can_cancel()

    # if the booking was made with a membership, allow 5 mins to cancel in case user
    # clicked the wrong button by mistake and autobooked with a membership
    # Check here so we can adjust the email message
    membership_booking_within_5_mins = (
        booking.booked_with_membership_within_allowed_time()
    )
    was_booked_with_membership = booking.membership is not None
    was_paid = booking.paid

    refunded = False
    if can_cancel_and_refund:
        if booking.membership:
            # booked with membership, remove from membership and set paid to False
            booking.membership = None
            booking.paid = False
        else:
            # Paid directly; find invoice/payment intent (if it exists), process refund
            if booking.invoice:
                refunded = process_refund(request, booking)

            # mark unpaid whether refunded or not
            # if there was no associated invoice, it was manually booked by an admin, or it wasn't paid yet
            booking.paid = False
        booking.status = "CANCELLED"
        booking.save()

    else:
        # The cancellation is being requested after the cancellation period, or for an event
        # that doesn't allow cancellation.  It can still be cancelled if:
        # - it wasn't paid OR
        # - it was just made with a membership: allow 5 mins to cancel in case user
        #   clicked the wrong button by mistake and autobooked with a membership
        can_cancel = membership_booking_within_5_mins or not booking.paid
        if can_cancel:
            booking.membership = None
            booking.paid = False
            booking.status = "CANCELLED"
            booking.save()
        else:  # set to no-show
            booking.no_show = True
            booking.save()

    # MESSAGES
    alert_message = {"level": "error"}
    # no messages if we're deleting from shopping basket
    if not delete_from_shopping_basket:
        alert_message["message"] = "Cancelled."
        if booking.status == "CANCELLED":
            if refunded:
                alert_message["message"] += " Refund processing."
            ActivityLog.objects.create(
                log="Booking id {} for event {}, user {}, was cancelled by user "
                "{}".format(
                    booking.id,
                    booking.event,
                    booking.user.username,
                    request.user.username,
                )
            )
        elif booking.no_show:
            if not booking.event.allow_booking_cancellation:
                alert_message["message"] += (
                    " Please note that this booking is not eligible for "
                    "refunds or transfer credit."
                )
                ActivityLog.objects.create(
                    log="Booking id {} for NON-CANCELLABLE event {}, user {}, "
                    "was cancelled and set to no-show".format(
                        booking.id,
                        booking.event,
                        booking.user.username,
                    )
                )
            else:
                alert_message["message"] += (
                    " Please note that this booking is not eligible for "
                    "refunds as the allowed cancellation period has passed."
                )
                ActivityLog.objects.create(
                    log="Booking id {} for event {}, user {}, was cancelled "
                    "after the cancellation period and set to "
                    "no-show".format(
                        booking.id,
                        booking.event,
                        booking.user.username,
                    )
                )

    # EMAIL USER
    # Only send emails if booking was previously paid; we don't want to send emails
    # if just removing from basket
    if was_paid:
        host = host_from_request(request)
        ctx = {
            "host": host,
            "booking": booking,
            "was_booked_with_membership": was_booked_with_membership,
            "membership_booked_within_allowed_time": membership_booking_within_5_mins,
            "refunded": refunded,
            "event": booking.event,
            "domain": settings.DOMAIN,
            "studio_email": settings.DEFAULT_STUDIO_EMAIL,
        }
        send_mail(
            "{} Booking for {} cancelled".format(
                settings.ACCOUNT_EMAIL_SUBJECT_PREFIX, booking.event
            ),
            get_template("booking/email/booking_cancelled.txt").render(ctx),
            settings.DEFAULT_FROM_EMAIL,
            [booking.user.email],
            html_message=get_template("booking/email/booking_cancelled.html").render(
                ctx
            ),
            fail_silently=False,
        )

        # EMAIL STUDIO
        if settings.SEND_ALL_STUDIO_EMAILS:
            send_mail(
                "{} Booking for {} cancelled".format(
                    settings.ACCOUNT_EMAIL_SUBJECT_PREFIX, booking.event
                ),
                get_template("booking/email/to_studio_booking_cancelled.txt").render(
                    ctx
                ),
                settings.DEFAULT_FROM_EMAIL,
                [settings.DEFAULT_STUDIO_EMAIL],
                fail_silently=False,
            )

    # WAITING LIST
    # if applicable, email users on waiting list
    email_waiting_lists([event.id], host=host)

    return alert_message

booking/views/memberships.py
import logging

from django.views.generic import ListView, DetailView

from braces.views import LoginRequiredMixin

from ..models import Membership
from .views_utils import DataPolicyAgreementRequiredMixin


logger = logging.getLogger(__name__)


class MembershipListView(
    DataPolicyAgreementRequiredMixin, LoginRequiredMixin, ListView
):
    model = Membership
    template_name = "booking/user_memberships.html"
    context_object_name = "memberships"
    paginate_by = 20

    def get_queryset(self):
        queryset = super().get_queryset()
        user_memberships = queryset.filter(user=self.request.user, paid=True).order_by(
            "year", "month", "purchase_date"
        )
        if not self.request.GET.get("include-expired"):
            user_memberships = [
                membership
                for membership in user_memberships
                if membership.current_or_future()
            ]
        return user_memberships

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["section"] = "membership"
        if self.request.GET.get("include-expired"):
            context["show_all"] = True
            context["title"] = "Active Memberships"
        else:
            context["title"] = "Memberships"
        return context


class MembershipDetailView(
    DataPolicyAgreementRequiredMixin, LoginRequiredMixin, DetailView
):
    model = Membership
    template_name = "booking/membership_detail.html"
    context_object_name = "membership"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["section"] = "membership"
        return context

website/templates/website/_base_legacy.html
{% load static %}
{% load django_bootstrap5 %}
{% load cookielaw_tags %}


<!DOCTYPE html>
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Sunshine Fitness</title>

        <link rel="icon" type="image/jpg" href="{% static 'website/images/logo_no_text.jpg' %}">
        <link rel="shortcut icon" href="{% static 'website/images/favicon.ico' %}" type="image/vnd.microsoft.icon">

        <!-- Bootstrap core CSS -->
        {% bootstrap_css %}

        <link href="{% static 'website/css/custom-legacy.css' %}" rel="stylesheet">
          <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" integrity="sha512-ELV+xyi8IhEApPS/pSj66+Jiw+sOT1Mqkzlh8ExXihe4zfqbWkxPRi8wptXIO9g73FSlhmquFlUOuMSoXz5IRw==" crossorigin="anonymous" referrerpolicy="no-referrer" />         
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/theme.min.css" integrity="sha512-hbs/7O+vqWZS49DulqH1n2lVtu63t3c3MTAn0oYMINS5aT8eIAbJGDXgLt6IxDHcWyzVTgf9XyzZ9iWyVQ7mCQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
          {% block extrahead %}{% endblock %}

    </head>
<body>

        <!-- Fixed navbar -->
<div class="navbar-wrap">
    <nav class="navbar navbar-expand-sm navbar-dark navbar-fixed">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img class="nav-logo" src="{% static 'website/images/logo_no_text.jpg' %}"></a>
    <div>
        <span class="d-inline d-sm-none">
            <a class="btn btn-warning btn-sm p-2" href="{% url 'booking:shopping_basket' %}">
                <span><i class="fas fa-shopping-cart"></i> <span class="badge badge-light" id="cart_item_menu_count_xs">{{ cart_item_count }}</span></span>
            </a>
        </span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item"><a class="nav-link{% if section == 'home' %} active{% endif %}" href="{% url 'website:home' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link{% if section == 'timetable' %} active{% endif %}" href="{% url 'timetable:timetable' %}">Timetable</a></li>
            {% if membership_types %}
            <li class="nav-item"><a class="nav-link{% if section == 'membership' %} active{% endif %}" href="{% url 'booking:membership_purchase' %}">Memberships</a>
            {% endif %}
            {% if gift_vouchers_available %}
                <li class="nav-item"><a class="nav-link{% if section == 'gift_voucher' %} active{% endif %}" href="{% url 'booking:buy_gift_voucher' %}">Gift Vouchers</a>
            {% endif %}
            <li class="nav-item"><a class="nav-link{% if section == 'booking' %} active{% endif %}" href="{% url 'booking:regular_session_list' %}">Book</a></li>
            <li class="nav-item"><a class="nav-link{% if section == 'contact' %} active{% endif %}" href="{% url 'website:contact' %}">Contact us</a></li>
        </ul>
        <ul class="navbar-nav">
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="btn btn-warning btn-sm p-2 mr-2" href="{% url 'booking:shopping_basket' %}">
                <span><i class="fas fa-shopping-cart"></i> <span class="badge badge-light" id="cart_item_menu_count">{{ cart_item_count }}</span></span>
                </a>
            </li>
            <li class="nav-item dropdown dropstart">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">My account<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li class="dropdown-item"><a class="account-menu-option" href="{% url 'accounts:profile' %}">Profile</a></li>
                    <li class="dropdown-item"><a class="account-menu-option" href="{% url 'account_change_password' %}">Change password</a></li>
                    <div class="dropdown-divider"></div>
                    <li class="dropdown-item"><a class="account-menu-option" href="{% url 'booking:bookings' %}">Bookings</a></li>
                    <li class="dropdown-item"><a class="account-menu-option" href="{% url 'booking:booking_history' %}">Booking history</a></li>
                    <li class="dropdown-item"><a class="account-menu-option" href="{% url 'booking:user_memberships' %}">Memberships</a></li>
                    <li class="dropdown-item"><a class="account-menu-option" href="{% url 'booking:transactions' %}">Payment history</a></li>
                    <div class="dropdown-divider"></div>
                    <li class="dropdown-item"><a class="account-menu-option" href="{% url 'account_logout' %}">Log out</a></li>

                    {% if user.is_staff or user.is_superuser %}
                        <div class="dropdown-divider"></div>
                        <li class="dropdown-item"><a class="account-menu-option" href="{% url 'studioadmin:regular_session_register_list' %}">Instructor Admin</a></li>
                    {% endif %}
                    {% if user.is_superuser %}
                        <li class="dropdown-item"><a class="account-menu-option" href="{% url 'admin:index' %}">Site Admin</a></li>
                    {% endif %}

                </ul>
            </li>
        {% else %}
            <li><a href="{% url 'account_login' %}">Log in</a></li>
        {% endif %}
        </ul>
    </div>
  </div>
</nav>

</div>

<div class="wrapper">
    <main role="main" class="container-fluid">

        {% cookielaw_banner %}

        {% block anon_banner %}
            {% if user.is_anonymous %}
                <div class="mb-4">
                    <div class="message alert alert-anon p-4">
                        <div><span class="fas fa-sun"></span> <a href={% url 'account_login' %}?next={{request.get_full_path|urlencode }}>Log in</a> to book a class! <span class="fas fa-sun"></span></div>
                    </div>
                </div>
            {% endif %}
        {% endblock anon_banner %}

        {% if messages %}
            <div class="extra-top-margin col-12">
                {% for message in messages %}
                <div {% if message.tags and message.tags == 'error' %}
                            class="message alert alert-danger"
                     {% elif message.tags %}
                            class="message alert alert-{{ message.tags }}"
                     {% endif %}>
                    {% if 'safe' in message.tags %}
                        {{ message|safe }}
                    {% else %}
                        {{ message }}
                    {% endif %}</div>
                {% endfor %}
            </div>
        {% endif %}

        <div class="container-fluid">
        {% block content %}
        <p>You need to define a content block!</p>
        {% endblock %}
        </div>


    </main> 
    </div>

    <footer class="footer">
            <span class="divider"></span>

        <div class="container-fluid">
            <div class="row footer_box">
                <div class="col-4 float-left">
                    <div class="footer-fb">
                    <a href="https://www.facebook.com/sunshinefitnessfife">
                        <span class="fab fa-facebook-square"></span>
                    </a>
                    <a href="https://www.instagram.com/sunshinefitnessfife">
                        <span class="fab fa-instagram"></span>
                    </a>
                    </div>
                    <div class="footer-credit"><a href="{% url 'data_privacy_policy' %}">Data Privacy Policy</a></div>
                </div>
                <div class="col-4 text-center">
		            <a class="footer-link" href="{% url 'website:contact' %}">Contact us</a> | <a href="{% url 'website:faq' %}">FAQ</a>
                </div>
                <div class="col-4 float-right">
                        <div class="footer-credit float-right">Site developed by <a href="https://twitter.com/rebkwok" target="_blank" style="color: #0B0B61">Becky Smith</a></div>
                </div>

            </div>
        </div>
    </footer>

</body>


    {% bootstrap_javascript %}

    <div id="fb-root"></div>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js" integrity="sha512-57oZ/vW8ANMjR/KQ6Be9v/+/h6bq9/l3f0Oc7vn6qMqyhvPd1cvKBRWWpzu0QoneImqr2SkmO4MSqU+RpHom3Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>    <script src="{% static 'website/js/custom-v3.js' %}"></script>
    <script src="{% static 'website/js/ajax_csrf.js' %}"></script>
    <script type="text/javascript" src="{% static 'cookielaw/js/cookielaw.js' %}"></script>

    {% block extrascripts %}{% endblock %}

</html>

website/templates/website/home_legacy.html
{% extends 'website/_base_legacy.html' %}
{% load static %}

{% block bg_class %}plain_bg{%  endblock %}

{% block content %}

<div class="container">

        <div class="row">
			<div class="col-12">
                <h1 class="page-header">Sunshine Fitness</h1>
            </div>
            <div class="col-12">
            <img class="img-fluid" src="{% static 'website/images/double_logo.jpg' %}" />
            </div>
            <div class="col-12">
                <p>
                    At Sunshine Fitness we offer fitness classes, personal training, one to ones and pride ourselves on bringing you
                    the highest quality pole dancing classes from the beautiful Sunshine Pole Studio. We run an all-inclusive,
                    safe environment, with a "come as you are" ethos!
                </p>

                <h2>Follow us</h2>
                <p><a href="https://www.instagram.com/sunshinefitnessfife">
                    <span class="text-warning fab fa-instagram fa-2x mr-2"></span> 
                </a>
                <a href="https://www.facebook.com/sunshinefitnessfife">
                    <span class="text-primary fab fa-facebook fa-2x"></span>
                </a></p>
                <p>#SunshineFitnessFife</p>


                <hr>
                <h2>Classes</h2>
                <p>Check out the <a href="{% url 'timetable:timetable' %}">timetable</a>, <a href={% url 'booking:regular_session_list' %}>book a class</a> or <a href="{% url 'website:contact' %}">contact us</a> for any other enquires.</p>
                {% if future_events.privates %}
                <p>Private lessons are also available; check available times and book <a href="{% url 'booking:private_list' %}">here</a>.<p>
                <hr>    
                {% endif %}
                {% if class_types %}
                    {% for class_type in class_types %}
                        <h3>{{ class_type.name }}</h3>
                        <p>{{ class_type.info }}
                    {% endfor %}

                {% endif %}
                <hr>

                {% include 'website/includes/membership_legacy.html' %}

		</div>
    </div>

</div>  <!-- container-fluid -->

{% endblock %}