accounts/urls.py
from django.urls import path

from .views import (
    profile,
    ProfileUpdateView,
    SignedDataPrivacyCreateView,
    DisclaimerCreateView,
    DisclaimerUpdateView,
    DisclaimerContactUpdateView,
)

app_name = "accounts"


urlpatterns = [
    path("profile/", profile, name="profile"),
    path("update/", ProfileUpdateView.as_view(), name="update_profile"),
    path(
        "data-privacy-review/",
        SignedDataPrivacyCreateView.as_view(),
        name="data_privacy_review",
    ),
    path(
        "disclaimer/<int:user_id>/update",
        DisclaimerUpdateView.as_view(),
        name="disclaimer_form_update",
    ),
    path(
        "disclaimer/<int:user_id>/",
        DisclaimerCreateView.as_view(),
        name="disclaimer_form",
    ),
    path(
        "emergency-contact/<int:user_id>/update/",
        DisclaimerContactUpdateView.as_view(),
        name="update_emergency_contact",
    ),
    path("", profile),
]

booking/urls.py
from django.urls import path
from django.views.generic import RedirectView


from booking.views import (
    RegularClassesEventListView,
    WorkshopEventListView,
    EventDetailView,
    PrivateClassesEventListView,
    BookingListView,
    BookingHistoryListView,
    toggle_waiting_list,
    shopping_basket_view,
    guest_shopping_basket,
    stripe_checkout,
    ajax_cart_item_delete,
    check_total,
    ajax_add_membership_to_basket,
    membership_purchase_view,
    MembershipListView,
    MembershipDetailView,
    GiftVoucherUpdateView,
    GiftVoucherPurchaseView,
    GiftVoucherDetailView,
    voucher_details,
    toggle_booking,
)
from booking.views.user_invoices_views import UserInvoiceListView


app_name = "booking"


urlpatterns = [
    path("my-bookings/", BookingListView.as_view(), name="bookings"),
    path("my-memberships/", MembershipListView.as_view(), name="user_memberships"),
    path(
        "membership-detail/<int:pk>/",
        MembershipDetailView.as_view(),
        name="membership_detail",
    ),
    path("booking-history/", BookingHistoryListView.as_view(), name="booking_history"),
    path(
        "classes/", RegularClassesEventListView.as_view(), name="regular_session_list"
    ),
    path("privates/", PrivateClassesEventListView.as_view(), name="private_list"),
    path("workshops/", WorkshopEventListView.as_view(), name="workshop_list"),
    path("event/<slug:slug>/", EventDetailView.as_view(), name="event_detail"),
    path("toggle-booking/<int:event_id>/", toggle_booking, name="toggle_booking"),
    path(
        "toggle-waiting-list/<int:event_id>/",
        toggle_waiting_list,
        name="toggle_waiting_list",
    ),
    # GIFT VOUCHERS
    path("gift-vouchers/", GiftVoucherPurchaseView.as_view(), name="buy_gift_voucher"),
    path(
        "gift-vouchers/<slug:slug>/update",
        GiftVoucherUpdateView.as_view(),
        name="gift_voucher_update",
    ),
    path(
        "gift-vouchers/<slug:slug>",
        GiftVoucherDetailView.as_view(),
        name="gift_voucher_details",
    ),
    path("voucher/<str:voucher_code>", voucher_details, name="voucher_details"),
    # MEMBERSHIPS
    path("memberships/", membership_purchase_view, name="membership_purchase"),
    path(
        "ajax-membership-purchase/",
        ajax_add_membership_to_basket,
        name="ajax_add_membership_to_basket",
    ),
    # SHOPPING BASKET
    path("shopping-basket/", shopping_basket_view, name="shopping_basket"),
    path("stripe-checkout/", stripe_checkout, name="stripe_checkout"),
    path("ajax-cart-item-delete/", ajax_cart_item_delete, name="ajax_cart_item_delete"),
    path("check-total/", check_total, name="check_total"),
    path("guest-shopping-basket/", guest_shopping_basket, name="guest_shopping_basket"),
    # transactions
    path("payment-history/", UserInvoiceListView.as_view(), name="transactions"),
    path("", RedirectView.as_view(url="/classes/", permanent=True)),
]

stripe_payments/urls.py
from django.urls import path
from .views import stripe_payment_complete, stripe_webhook
from .connection_views import (
    connect_stripe_view,
    StripeAuthorizeView,
    StripeAuthorizeCallbackView,
)


app_name = "stripe_payments"

urlpatterns = [
    # connecting stripe seller account
    path("stripe/connect/", connect_stripe_view, name="connect_stripe"),
    path("stripe/authorize/", StripeAuthorizeView.as_view(), name="authorize_stripe"),
    path(
        "stripe/oauth/callback/",
        StripeAuthorizeCallbackView.as_view(),
        name="authorize_stripe_callback",
    ),
    # transactions
    path(
        "stripe-payment-complete/",
        stripe_payment_complete,
        name="stripe_payment_complete",
    ),
    path("stripe/webhook/", stripe_webhook, name="stripe_webhook"),
]

sunshine/urls.py
from django.urls import include, path, re_path

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import (
    CustomLoginView,
    CustomSignUpView,
    data_privacy_policy,
    cookie_policy,
)
from booking.views import permission_denied
from studioadmin.views.views import redirect_to_admin

urlpatterns = [
    path("", include("website.urls")),
    path("accounts/signup/", CustomSignUpView.as_view(), name="account_signup"),
    path("accounts/login/", CustomLoginView.as_view(), name="account_login"),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("data-privacy-policy/", data_privacy_policy, name="data_privacy_policy"),
    path("cookie-policy/", cookie_policy, name="cookie_policy"),
    re_path(r"^pf_admin.*", redirect_to_admin, name="redirect_old_link"),
    path("instructor-admin/", include("studioadmin.urls")),
    path("site-admin/", admin.site.urls),
    path("booking/", include("booking.urls")),
    path("timetable/", include("timetable.urls")),
    path("payments/", include("stripe_payments.urls")),
    path("not-available/", permission_denied, name="permission_denied"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:  # pragma: no cover
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

admin.autodiscover()
admin.site.site_header = "Sunshine Fitness"
admin.site.enable_nav_sidebar = False

booking/models.py
# -*- coding: utf-8 -*-
from calendar import monthrange, month_name, month_abbr
from datetime import datetime, timedelta
from datetime import timezone as dt_timezone

from dateutil.relativedelta import relativedelta
from decimal import Decimal
import logging
import pytz
import shortuuid

from django.db import models
from django.db.models import Q
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from django_extensions.db.fields import AutoSlugField

from activitylog.models import ActivityLog
from stripe_payments.models import Invoice
from timetable.models import Venue
from booking.utils import (
    start_of_day_in_utc,
    end_of_day_in_utc,
    start_of_day_in_local_time,
)

logger = logging.getLogger(__name__)


EVENT_TYPE_CHOICES = (
    ("workshop", "Workshop"),
    ("regular_session", "Regular Timetabled Session"),
    ("private", "Private Lesson"),
)
GIFT_VOUCHER_EVENT_TYPES = (
    ("regular_session", "Class"),
    ("private", "Private Lesson"),
    ("workshop", "Workshop"),
)


class Event(models.Model):
    EVENT_TYPES = EVENT_TYPE_CHOICES

    name = models.CharField(max_length=255)
    event_type = models.CharField(
        choices=EVENT_TYPES, default="regular_session", max_length=255
    )
    description = models.TextField(blank=True, default="")
    date = models.DateTimeField()
    venue = models.ForeignKey(Venue, null=True, on_delete=models.SET_NULL)
    max_participants = models.PositiveIntegerField(default=12)

    contact_email = models.EmailField(default="sunshinefitnessfife@gmail.com")
    cost = models.DecimalField(max_digits=8, decimal_places=2)

    show_on_site = models.BooleanField(
        default=False,
        help_text="Display this event/workshop on the website "
        "(if unticked, it will still be displayed for staff users "
        "for preview)",
    )

    cancellation_period = models.PositiveIntegerField(default=24)
    email_studio_when_booked = models.BooleanField(default=False)
    slug = AutoSlugField(populate_from=["name", "date"], max_length=40, unique=True)
    allow_booking_cancellation = models.BooleanField(default=True)
    cancelled = models.BooleanField(default=False)
    cancellation_fee = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    members_only = models.BooleanField(
        default=False,
        help_text="Classes are only available to students with memberships",
    )

    class Meta:
        ordering = ["-date"]
        verbose_name = "Workshop/Class"
        verbose_name_plural = "Workshops/Classes"
        indexes = [
            models.Index(fields=["date", "event_type"]),
        ]

    @property
    def spaces_left(self):
        booked_number = (
            Booking.objects.select_related("event", "user")
            .filter(event__id=self.id, status="OPEN", no_show=False)
            .count()
        )
        return self.max_participants - booked_number

    @property
    def bookable(self):
        return self.spaces_left > 0 and not self.cancelled

    def can_cancel(self):
        now = timezone.now()
        time_until_event = self.date - timezone.now()
        time_until_event = time_until_event.total_seconds() / 3600
        # adjust cancellation period if now and event date are in different DST states
        # in spring, if it's currently before DST and the class is after DST, we need to decrease the
        # cancellation period by 1 hour i.e.
        # - currently it is 9.30am and NOT DST
        # - class is tomorrow at 10am and IS DST
        # Only 23.5 actual hrs between now and class time, but user would expect to be able to cancel
        # if cancellation period is 24 hrs

        # Only bother checking if it's currently March or October; DST only has an impact on cancellations
        # made within a day or two (depending on cancellation time) of event date
        cancellation_period = self.cancellation_period
        if now.month in [3, 10]:
            local_tz = pytz.timezone("Europe/London")
            now_local = now.astimezone(local_tz)
            event_date_local = self.date.astimezone(local_tz)
            # find the difference in DST offset between now and the event date (in hours)
            dst_diff_in_hrs = (
                now_local.dst().seconds - event_date_local.dst().seconds
            ) / (60 * 60)
            # add this to the cancellation period
            # For spring, this means now (0 offset) minus event date (1 hr offset) == -1 hour
            # We subtract 1 hour from the cancellation period, so for a 24 hr cancellation users can
            # cancel in the 23 hrs before
            # For Autumn we add 1 hour, so the cancellation period is 1 hr more
            cancellation_period += dst_diff_in_hrs
        return self.allow_booking_cancellation and (
            time_until_event > cancellation_period
        )

    def get_available_user_membership(self, user):
        if self.event_type != "regular_session":
            # memberships are only valid for regular classes
            return None
        valid_memberships = user.memberships.filter(
            month=self.date.month, year=self.date.year, paid=True
        ).order_by("purchase_date")
        available = next(
            (membership for membership in valid_memberships if not membership.full()),
            None,
        )
        return available

    def __str__(self):
        local_datestr = self.date.astimezone(pytz.timezone("Europe/London")).strftime(
            "%d %b %Y, %H:%M"
        )
        return f"{self.name} - {local_datestr}"

    @classmethod
    def active_locations(cls):
        locations_in_order = list(Venue.distinct_locations_in_order())
        active_locations = set(
            cls.objects.filter(
                show_on_site=True, cancelled=False, date__gt=timezone.now()
            ).values_list("venue__location__name", flat=True)
        )
        return sorted(active_locations, key=lambda x: locations_in_order.index(x))


class MembershipType(models.Model):
    name = models.CharField(max_length=255)
    number_of_classes = models.PositiveIntegerField()
    cost = models.DecimalField(max_digits=8, decimal_places=2)
    active = models.BooleanField(
        default=True, help_text="Visible and available for purchase on site"
    )

    def __str__(self) -> str:
        return f"{self.name} - £{self.cost:.2f}"


def _start_of_today():
    now = timezone.now()
    return start_of_day_in_local_time(now)


class BaseVoucher(models.Model):
    code = models.CharField(max_length=255, unique=True)
    discount = models.PositiveIntegerField(
        verbose_name="Percentage discount",
        help_text="Discount value as a % of the purchased item cost. Enter a number between 1 and 100",
        null=True,
        blank=True,
    )
    discount_amount = models.DecimalField(
        verbose_name="Exact discount amount (£)",
        help_text="Discount as an exact amount off the purchased item cost",
        null=True,
        blank=True,
        decimal_places=2,
        max_digits=6,
    )
    start_date = models.DateTimeField(default=_start_of_today)
    expiry_date = models.DateTimeField(null=True, blank=True)
    max_vouchers = models.PositiveIntegerField(
        null=True,
        blank=True,
        verbose_name="Maximum available vouchers",
        help_text="Maximum uses across all users",
    )
    max_per_user = models.PositiveIntegerField(
        null=True,
        blank=True,
        verbose_name="Maximum uses per user",
        help_text="Maximum times this voucher can be used by a single user",
    )

    # for gift vouchers
    is_gift_voucher = models.BooleanField(default=False)
    activated = models.BooleanField(default=True)
    name = models.CharField(
        null=True, blank=True, max_length=255, help_text="Name of recipient"
    )
    message = models.TextField(
        null=True, blank=True, max_length=500, help_text="Message (max 500 characters)"
    )
    purchaser_email = models.EmailField(null=True, blank=True)

    @property
    def has_expired(self):
        if self.expiry_date and self.expiry_date < timezone.now():
            return True
        return False

    @property
    def has_started(self):
        return bool(self.start_date < timezone.now() and self.activated)

    def clean(self):
        if not (self.discount or self.discount_amount):
            raise ValidationError(
                "One of discount (%) or discount amount (fixed £ amount) is required"
            )
        if self.discount and self.discount_amount:
            raise ValidationError(
                "Only one of discount (%) or discount amount (fixed £ amount) may be specified (not both)"
            )

    def _generate_code(self):
        return slugify(shortuuid.ShortUUID().random(length=12))

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = self._generate_code()
            while BaseVoucher.objects.filter(code=self.code).exists():
                self.code = self._generate_code()
        self.full_clean()
        # replace start time with very start of day
        self.start_date = start_of_day_in_utc(self.start_date)
        if self.expiry_date:
            self.expiry_date = end_of_day_in_utc(self.expiry_date)
        super().save(*args, **kwargs)

    def __str__(self):
        if self.discount:
            return f"{self.code} - {self.discount}%"
        else:
            return f"{self.code} - £{self.discount_amount:.2f}"


class ItemVoucher(BaseVoucher):

booking/views/misc.py
from django.http import HttpResponseForbidden
from django.template import loader


def csrf_failure(request, reason=""):
    context = {"request": request, "back_url": request.META.get("HTTP_REFERER", "/")}
    template = loader.get_template("403_csrf.html")
    return HttpResponseForbidden(template.render(context))

booking/views/user_invoices_views.py
import logging

from django.views.generic import ListView

from braces.views import LoginRequiredMixin

from stripe_payments.models import Invoice


logger = logging.getLogger(__name__)


class UserInvoiceListView(LoginRequiredMixin, ListView):
    paginate_by = 20
    model = Invoice
    context_object_name = "invoices"
    template_name = "booking/invoices.html"

    def get_queryset(self):
        return Invoice.objects.filter(paid=True, username=self.request.user.email)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["section"] = "account"
        return context

booking/templates/booking/shopping_basket.html
{% extends "website/_base.html" %}
{% load static %}
{% load accounttags bookingtags %}

{% block extrahead %}
{% include 'booking/includes/ajax_head.html' %}
{% endblock %}


{% block title %}
    {% include "website/includes/header.html" with title="Shopping Basket" %}
{% endblock %}


{% block content %}

<section>
    <div class="container mt-20">
    
        {% if unpaid_items %}

            <table class="table table-bordered">
              <thead class="table-dark">
                <tr>
                  <th>Item</th>
                  <th>Cost</th>
                </tr>
              </thead>
              <tbody>
                {% if unpaid_membership_info %}
                    <tr><td colspan="2" class="table-secondary"><strong>Memberships</strong></td></tr>
                {% endif %}
                {% for membership_info in unpaid_membership_info %}
                    <tr id="cart-row-membership-{{ membership_info.membership.id }}" class="cart-row-membership">
                        <td class="p-1">{{ membership_info.membership }}</td>
                        <td class="p-1">
                            <div>Cost: {% if membership_info.voucher_applied.discounted_cost is not None %}
                                    <span class="superceded-cost">£{{ membership_info.original_cost }}</span> £{{ membership_info.voucher_applied.discounted_cost }}
                                {% else %}
                                    £{{ membership_info.original_cost }}
                                {% endif %}
                            {% if membership_info.voucher_applied.discounted_cost is not None %}
                            <br><span class="text-secondary"><small><em>Voucher code applied: {{ membership_info.voucher_applied.code }}</em></small></span>
                            {% endif %}
                            <span
                                    id="remove-membership-{{ membership_info.membership.id }}"
                                    class="remove-membership float-end"
                                    data-membership_id="{{ membership_info.membership.id }}"
                                    >
                                <a class="btn btn-sm btn-pink tra-pink-hover" href="#"><i class="fas fa-trash-alt"></i></a>
                            </span>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                
                {% if unpaid_booking_info %}
                    <tr><td colspan="2" class="table-secondary">
                        <strong>Classes and Workshops</strong><br/>
                        <span class="text-danger">
                            NOTE: classes and workshop items will be removed from basket after {{ cart_timeout_mins }} minutes
                        </span>
                        <div id="countdown"></div>
                    </td></tr>
                    
                {% endif %}
                {% for booking_info in unpaid_booking_info %}
                <tr id="cart-row-booking-{{ booking_info.booking.id }}" class="cart-row-booking">
                    <td class="p-1">{{ booking_info.booking.event }}</td>
                    <td class="p-1">
                        <div>Cost: {% if booking_info.voucher_applied.discounted_cost is not None %}
                                <span class="superceded-cost">£{{ booking_info.original_cost }}</span> £{{ booking_info.voucher_applied.discounted_cost }}
                            {% else %}
                                £{{ booking_info.original_cost }}
                            {% endif %}
                        {% if booking_info.voucher_applied.discounted_cost is not None %}
                        <br><span class="text-secondary"><small><em>Voucher code applied: {{ booking_info.voucher_applied.code }}</em></small></span>
                        {% endif %}
                        <span
                                id="remove-booking-{{ booking_info.booking.id }}"
                                class="remove-booking float-end"
                                data-booking_id="{{ booking_info.booking.id }}"
                                >
                            <a class="btn btn-sm btn-pink tra-pink-hover" href="#"><i class="fas fa-trash-alt"></i></a>
                        </span>
                        </div>
                    </td>
                </tr>
                {% endfor %}

                {% if unpaid_gift_voucher_info %}
                    <tr><td colspan="2" class="table-secondary"><strong>Gift Vouchers</strong></td></tr>
                {% endif %}
                {% for gift_voucher_info in unpaid_gift_voucher_info %}
                    <tr id="cart-row-gift-voucher-{{ gift_voucher_info.gift_voucher.id }}">
                        <td class="p-1">{{ gift_voucher_info.gift_voucher.name }}
                            <a class="text-success" href="{% url 'booking:gift_voucher_update' gift_voucher_info.gift_voucher.slug %}"><span class="fas fa-edit"></span></a>
                        </td>
                        <td class="p-1">
                            <div>Cost: £{{ gift_voucher_info.gift_voucher.gift_voucher_type.cost }}
                                <span
                                        id="remove-gift-voucher-{{ gift_voucher_info.gift_voucher.id }}"
                                        class="remove-gift-voucher float-end"
                                        data-gift_voucher_id="{{ gift_voucher_info.gift_voucher.id }}"
                                        >
                                    <a class="btn btn-sm btn-pink tra-pink-hover" href="#"><i class="fas fa-trash-alt"></i></a>
                                </span>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            
                </tbody>
              <tfoot>
              <tr>
                  <td colspan="2">
                      <strong>TOTAL:
                          {% if total_cost_without_total_voucher != total_cost %}
                                <span class="superceded-cost">£{{ total_cost_without_total_voucher }}</span>
                          {% endif %}
                          £ <span id="total">{{ total_cost }}</span></strong>
                    {% if total_cost_without_total_voucher != total_cost %}
                        <span class="text-secondary"><small><em> (voucher code applied: {{ request.session.total_voucher_code }})</em></small></span>{% endif %}
                      
                      <form method="post" action="{% url 'booking:stripe_checkout' %}">
                          {% csrf_token %}
                          <input type="hidden" name="cart_total" id="cart_total_input" value="{{ total_cost }}">
                          <input
                                  class="btn btn-sunshine tra-sunshine-hover mb-1"
                                  type="submit"
                                  value="{% if total_cost > 0 %}Checkout{% else %}Submit{% endif %}"
                          />
                      </form>

                      <div>Add additional items:<br/>
                      {% if request.user.is_authenticated %}
                        {% if membership_types %}
                        <a class="btn btn-sm btn-tra-sunshine sunshine-hover" href="{% url 'booking:membership_purchase' %}">Membership</a>
                        {% endif %}
                        <a class="btn btn-sm btn-tra-sunshine sunshine-hover" href="{% url 'booking:regular_session_list' %}">Class</a>
                        {% if future_events.privates %}
                            <a class="btn btn-sm btn-tra-sunshine sunshine-hover" href="{% url 'booking:private_list' %}">Private</a>
                        {% endif %}
                        {% if future_events.workshops %}  
                            <a class="btn btn-sm btn-tra-sunshine sunshine-hover" href="{% url 'booking:workshop_list' %}">Workshop</a>
                        {% endif %}
                      {% endif %}
                      {% if gift_vouchers_available %}
                      <a class="btn btn-sm btn-tra-sunshine sunshine-hover" href="{% url 'booking:buy_gift_voucher' %}">Gift vouchers</a>
                      {% endif %}  
                    </div>
                      {% if request.user.is_authenticated %}
                      <hr>
                          <form name="voucher_form" class="form-inline" method="post" action="">
                            {% csrf_token %}
                            <input name="code" type="text" required="required"/>
                            <input class="btn btn-sm btn-sunshine tra-sunshine-hover ml-2" type="submit" name="add_voucher_code" value="Apply voucher code"/>
                        </form>
                        <span class="errorlist"><ul>{% for error in voucher_add_error %}<li>{{ error }}</li>{% endfor %}</ul></span>
                      {% if applied_voucher_codes_and_discount %}
                      <hr class="mb-2">
                      <div><small><strong>Codes applied:</strong></small>
                          {% for applied_voucher_code, applied_voucher_discount, applied_voucher_discount_amount in applied_voucher_codes_and_discount %}
                                <form class="form-inline mt-0 mb-1" method="post" action="">
                                    {% csrf_token %}
                                    <input name="code" type="hidden" value="{{ applied_voucher_code }}"/>
                                    <span class="mr-1 m-0 pb-1 pl-1 pr-1 pt-0 alert alert-info"><small><strong>{{ applied_voucher_code }}</strong> ({% if applied_voucher_discount %}{{ applied_voucher_discount }}%{% else %}£{{ applied_voucher_discount_amount }}{%  endif %} off)</small></span>
                                    <button type="submit" name="remove_voucher_code" class="btn btn-sm btn-pink tra-pink-hover pb-1 pl-2 pr-2 pt-0"><small><i class="fas fa-trash-alt"></i></small></button>
                                    <button type="submit" name="refresh_voucher_code" class="btn btn-sm btn-cherry tra-cherry-hover pb-1 pl-2 pr-2 pt-0 ml-1"><small><i class="fas fa-sync-alt"></i></small></button>
                                </form>
                            {% endfor %}
                     </div>
                      {% endif %}
                    {% endif %}
                  </td>
              </tr>
              </tfoot>
            </table>

        {% else %}
            <div class="col-12">
            <p>Your cart is empty</p>
            {% if request.user.is_authenticated %}
            <p>
                {% if membership_types %}
                    <a class="btn btn-sm btn-tra-sunshine sunshine-hover" href="{% url 'booking:membership_purchase' %}">Add membership</a>
                {% endif %}
                <a class="btn btn-sm btn-tra-sunshine sunshine-hover" href="{% url 'booking:regular_session_list' %}">Add classes</a>
                {% if future_events.privates %}
                    <a class="btn btn-sm btn-tra-sunshine sunshine-hover" href="{% url 'booking:private_list' %}">Add private lessons</a>
                {% endif %}
                {% if future_events.workshops %}  
                    <a class="btn btn-sm btn-tra-sunshine sunshine-hover" href="{% url 'booking:workshop_list' %}">Add workshops</a>
                {% endif %}
                {% if gift_vouchers_available %}
                <a class="btn btn-sm btn-tra-sunshine sunshine-hover" href="{% url 'booking:buy_gift_voucher' %}">Add gift vouchers</a>
                {% endif %} 
            </p>
            {% endif %}
            </div>
        {% endif %}
    
    </div>
</section>

{% endblock content %}


{% block extrascripts %}
<script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
<script type='text/javascript' src="{% static 'booking/js/shopping_basket_ajax.js' %}"></script>
{% endblock %}

booking/templates/booking/user_memberships.html
{% extends "website/_base.html" %}

{% load accounttags bookingtags static %}

{% block extrahead %}
{% include 'booking/includes/ajax_head.html' %}
{% endblock %}

{% block title %}
    {% include "website/includes/header.html" with title=title %}
{% endblock %}

{% block content %}

<section>

    <div class="container mt-20">

        <div class="row">
            <div class="col-8">
                {% if show_all %}
                    <a href="{% url 'booking:user_memberships' %}">Hide expired/full</a>
                {% else %}
                    <a href="{% url 'booking:user_memberships' %}?include-expired=true">Show all (including expired/full)</a>
                {% endif %}
            </div>
            {% if membership_types %}
            <div class="col-4 mb-2">
                <a class="btn btn-sm  btn-sunshine tra-sunshine-hover"href="{% url 'booking:membership_purchase' %}">Buy a new membership</a>
            </div>
            {% endif %}

            <div class="col-12">
            {% if memberships %}
                {% for membership in memberships %}
                <div class="list-group mb-2">
                    <div class="list-group-item list-group-item-dark pt-1 pb-1">{{ membership }}
                        <a href="{% url 'booking:membership_detail' membership.id %}" class="btn btn-sm btn-color-01 tra-01-hover float-end">View details</a>
                    </div>
                    <div class="list-group-item {% if not membership.current_or_future %}list-group-item-secondary{% endif %} pb-0 pt-0">
                        <strong>Purchased:</strong> {{ membership.purchase_date | date:"d-M-Y" }}
                        <br/>
                        <strong>Valid for: </strong>Classes in {{ membership.month_str }} {{ membership.year }}<br/>
                        <strong>Number of classes:</strong> {{ membership.membership_type.number_of_classes }}
                        <br>
                        <strong>Bookings made:</strong> {{ membership.times_used }}
                    </div>
                </div>
                {% endfor %}

            {% else %}
                <p>No memberships found.</p>
            {% endif %}
            </div>
            {% include 'booking/includes/pagination.html' %}
        </div>

    </div>
</section>
{% endblock content %}