accounts/urls.py
from django.urls import path

from .views import (
    profile,
    ProfileUpdateView,
    SignedDataPrivacyCreateView,
    DisclaimerCreateView,
    DisclaimerUpdateView,
    DisclaimerContactUpdateView,
)

app_name = "accounts"


urlpatterns = [
    path("profile/", profile, name="profile"),
    path("update/", ProfileUpdateView.as_view(), name="update_profile"),
    path(
        "data-privacy-review/",
        SignedDataPrivacyCreateView.as_view(),
        name="data_privacy_review",
    ),
    path(
        "disclaimer/<int:user_id>/update",
        DisclaimerUpdateView.as_view(),
        name="disclaimer_form_update",
    ),
    path(
        "disclaimer/<int:user_id>/",
        DisclaimerCreateView.as_view(),
        name="disclaimer_form",
    ),
    path(
        "emergency-contact/<int:user_id>/update/",
        DisclaimerContactUpdateView.as_view(),
        name="update_emergency_contact",
    ),
    path("", profile),
]

booking/urls.py
from django.urls import path
from django.views.generic import RedirectView


from booking.views import (
    RegularClassesEventListView,
    WorkshopEventListView,
    EventDetailView,
    PrivateClassesEventListView,
    BookingListView,
    BookingHistoryListView,
    toggle_waiting_list,
    shopping_basket_view,
    guest_shopping_basket,
    stripe_checkout,
    ajax_cart_item_delete,
    check_total,
    ajax_add_membership_to_basket,
    membership_purchase_view,
    MembershipListView,
    MembershipDetailView,
    GiftVoucherUpdateView,
    GiftVoucherPurchaseView,
    GiftVoucherDetailView,
    voucher_details,
    toggle_booking,
)
from booking.views.user_invoices_views import UserInvoiceListView


app_name = "booking"


urlpatterns = [
    path("my-bookings/", BookingListView.as_view(), name="bookings"),
    path("my-memberships/", MembershipListView.as_view(), name="user_memberships"),
    path(
        "membership-detail/<int:pk>/",
        MembershipDetailView.as_view(),
        name="membership_detail",
    ),
    path("booking-history/", BookingHistoryListView.as_view(), name="booking_history"),
    path(
        "classes/", RegularClassesEventListView.as_view(), name="regular_session_list"
    ),
    path("privates/", PrivateClassesEventListView.as_view(), name="private_list"),
    path("workshops/", WorkshopEventListView.as_view(), name="workshop_list"),
    path("event/<slug:slug>/", EventDetailView.as_view(), name="event_detail"),
    path("toggle-booking/<int:event_id>/", toggle_booking, name="toggle_booking"),
    path(
        "toggle-waiting-list/<int:event_id>/",
        toggle_waiting_list,
        name="toggle_waiting_list",
    ),
    # GIFT VOUCHERS
    path("gift-vouchers/", GiftVoucherPurchaseView.as_view(), name="buy_gift_voucher"),
    path(
        "gift-vouchers/<slug:slug>/update",
        GiftVoucherUpdateView.as_view(),
        name="gift_voucher_update",
    ),
    path(
        "gift-vouchers/<slug:slug>",
        GiftVoucherDetailView.as_view(),
        name="gift_voucher_details",
    ),
    path("voucher/<str:voucher_code>", voucher_details, name="voucher_details"),
    # MEMBERSHIPS
    path("memberships/", membership_purchase_view, name="membership_purchase"),
    path(
        "ajax-membership-purchase/",
        ajax_add_membership_to_basket,
        name="ajax_add_membership_to_basket",
    ),
    # SHOPPING BASKET
    path("shopping-basket/", shopping_basket_view, name="shopping_basket"),
    path("stripe-checkout/", stripe_checkout, name="stripe_checkout"),
    path("ajax-cart-item-delete/", ajax_cart_item_delete, name="ajax_cart_item_delete"),
    path("check-total/", check_total, name="check_total"),
    path("guest-shopping-basket/", guest_shopping_basket, name="guest_shopping_basket"),
    # transactions
    path("payment-history/", UserInvoiceListView.as_view(), name="transactions"),
    path("", RedirectView.as_view(url="/classes/", permanent=True)),
]

sunshine/urls.py
from django.urls import include, path, re_path

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import (
    CustomLoginView,
    CustomSignUpView,
    data_privacy_policy,
    cookie_policy,
)
from booking.views import permission_denied
from studioadmin.views.views import redirect_to_admin

urlpatterns = [
    path("", include("website.urls")),
    path("accounts/signup/", CustomSignUpView.as_view(), name="account_signup"),
    path("accounts/login/", CustomLoginView.as_view(), name="account_login"),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("data-privacy-policy/", data_privacy_policy, name="data_privacy_policy"),
    path("cookie-policy/", cookie_policy, name="cookie_policy"),
    re_path(r"^pf_admin.*", redirect_to_admin, name="redirect_old_link"),
    path("instructor-admin/", include("studioadmin.urls")),
    path("site-admin/", admin.site.urls),
    path("booking/", include("booking.urls")),
    path("timetable/", include("timetable.urls")),
    path("payments/", include("stripe_payments.urls")),
    path("not-available/", permission_denied, name="permission_denied"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:  # pragma: no cover
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

admin.autodiscover()
admin.site.site_header = "Sunshine Fitness"
admin.site.enable_nav_sidebar = False

accounts/forms.py
from copy import deepcopy
from dateutil.relativedelta import relativedelta

from django import forms
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.utils.html import mark_safe, linebreaks

from crispy_forms.helper import FormHelper
from crispy_forms.layout import (
    Layout,
    Submit,
    Hidden,
    HTML,
)

from accounts import validators as account_validators
from .models import (
    DataPrivacyPolicy,
    SignedDataPrivacy,
    OnlineDisclaimer,
    DisclaimerContent,
    has_expired_disclaimer,
)


class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=30, label="First name")
    last_name = forms.CharField(max_length=30, label="Last name")

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        # get the current version here to make sure we always display and save
        # with the same version, even if it changed while the form was being
        # completed
        if DataPrivacyPolicy.current():
            self.data_privacy_policy = DataPrivacyPolicy.current()
            self.fields["content"] = forms.CharField(
                initial=self.data_privacy_policy.content, required=False
            )
            self.fields["data_privacy_confirmation"] = forms.BooleanField(
                widget=forms.CheckboxInput(attrs={"class": "regular-checkbox"}),
                required=False,
                label="I confirm I have read and agree to the terms of the data "
                "privacy policy",
            )

    def clean_data_privacy_confirmation(self):
        dp = self.cleaned_data.get("data_privacy_confirmation")
        if not dp:
            self.add_error(
                "data_privacy_confirmation", "You must check this box to continue"
            )
        return

    def signup(self, request, user):
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.save()
        if hasattr(self, "data_privacy_policy"):
            SignedDataPrivacy.objects.create(
                user=user,
                version=self.data_privacy_policy.version,
                date_signed=timezone.now(),
            )


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
        )
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
        }


class DataPrivacyAgreementForm(forms.Form):
    confirm = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={"class": "regular-checkbox"}),
        required=False,
        label="I confirm I have read and agree to the terms of the data privacy policy",
    )

    def __init__(self, *args, **kwargs):
        self.next_url = kwargs.pop("next_url")
        super(DataPrivacyAgreementForm, self).__init__(*args, **kwargs)
        self.data_privacy_policy = DataPrivacyPolicy.current()

    def clean_confirm(self):
        confirm = self.cleaned_data.get("confirm")
        if not confirm:
            self.add_error("confirm", "You must check this box to continue")
        return


BASE_DISCLAIMER_FORM_WIDGETS = {
    "phone": forms.TextInput(attrs={"class": "form-control"}),
    "emergency_contact_name": forms.TextInput(
        attrs={"class": "form-control", "autofocus": "autofocus"}
    ),
    "emergency_contact_relationship": forms.TextInput(attrs={"class": "form-control"}),
    "emergency_contact_phone": forms.TextInput(attrs={"class": "form-control"}),
}


class DisclaimerForm(forms.ModelForm):
    terms_accepted = forms.BooleanField(
        required=True,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}),
        label="Please tick to accept terms.",
    )
    password = forms.CharField(
        widget=forms.PasswordInput(),
        label="Please re-enter your password to confirm.",
        required=True,
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("disclaimer_user")
        super().__init__(*args, **kwargs)

        if self.instance.id:
            self.disclaimer_content = DisclaimerContent.objects.get(
                version=self.instance.version
            )
        else:
            self.disclaimer_content = DisclaimerContent.current()

        self.fields["health_questionnaire_responses"].required = any(
            field.get("required") for field in self.disclaimer_content.form
        )
        self.fields["date_of_birth"] = forms.DateField(
            widget=forms.DateInput(
                attrs={"autocomplete": "off", "class": "form-control"},
                format="%d-%b-%Y",
            ),
            input_formats=["%d-%b-%Y"],
            help_text="Minimum age for registering and booking classes is 16",
        )
        self.fields["emergency_contact_phone"].validators = [
            account_validators.phone_number_validator
        ]
        self.fields["phone"].validators = [account_validators.phone_number_validator]
        self.fields["phone"].label = "Contact phone number"
        if self.user is not None:
            if has_expired_disclaimer(self.user):
                last_disclaimer = OnlineDisclaimer.objects.filter(user=self.user).last()
                # set initial on all fields except password and confirmation fields
                # to data from last disclaimer
                for field_name in self.fields:
                    if field_name not in ["terms_accepted", "password"]:
                        last_value = getattr(last_disclaimer, field_name)
                        self.fields[field_name].initial = last_value
        self.helper = FormHelper()
        back_url = reverse("accounts:profile")

        # Add a cancel button if we're updating a disclaimer
        buttons = [
            Submit("submit", "Save", css_class="btn-sunshine btn-xs tra-sunshine-hover")
        ]
        if self.instance.id:
            buttons.append(
                HTML(
                    f'<a class="btn  btn-xs btn-color-01 tra-01-hover" href="{back_url}">Cancel</a>'
                )
            )
        self.helper.layout = Layout(
            HTML("<h3>Your details</h3>"),
            "phone",
            "date_of_birth",
            HTML("<h3>Emergency Contact Information</h3>"),
            HTML(
                "<p>Your emergency contact will be contacted in the case of an accident or emergency.</p>"
            ),
            "emergency_contact_name",
            "emergency_contact_phone",
            "emergency_contact_relationship",
            HTML("<h3>Physical Activity Readiness Questionnaire</h3>"),
            "health_questionnaire_responses",
            HTML(
                '<p>If you have answered "Yes" to any of the above questions, please consult your doctor before '
                "you participate in a class/event/workshop</p>"
            ),
            HTML("<h3>Waiver</h3>"),
            HTML(mark_safe(linebreaks(self.disclaimer_content.disclaimer_terms))),
            "terms_accepted",
            "password",
            Hidden("user", self.user.id),
            Hidden("version", self.disclaimer_content.version),
            *buttons,
        )

    class Meta:
        model = OnlineDisclaimer
        fields = (
            "terms_accepted",
            "emergency_contact_name",
            "date_of_birth",
            "phone",
            "emergency_contact_relationship",
            "emergency_contact_phone",
            "health_questionnaire_responses",
            "user",
            "version",
        )
        widgets = deepcopy(BASE_DISCLAIMER_FORM_WIDGETS)

    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data.get("date_of_birth")
        age_cutoff_date = (timezone.now() - relativedelta(years=16)).date()
        if date_of_birth > age_cutoff_date:
            self.add_error(
                "date_of_birth",
                "You must be at least 16 years old to register and book classes",
            )
            return
        return date_of_birth

    def clean_password(self):
        password = self.cleaned_data.get("password")
        if self.user.check_password(password):
            return password
        self.add_error("password", "Invalid password entered")


class DisclaimerContactUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["emergency_contact_phone"].validators = []
        self.fields["phone"].validators = [account_validators.phone_number_validator]
        self.fields["phone"].label = "Contact phone number"

        self.helper = FormHelper()
        back_url = reverse("accounts:profile")
        self.helper.layout = Layout(
            "phone",
            "emergency_contact_name",
            "emergency_contact_phone",
            "emergency_contact_relationship",
            Submit("submit", "Save", css_class="btn btn-green tra-green-hover"),
            HTML(
                f'<a class="btn btn-color-01 tra-01-hover" href="{back_url}">Cancel</a>'
            ),
        )

    class Meta:
        model = OnlineDisclaimer
        fields = (
            "phone",
            "emergency_contact_name",
            "emergency_contact_relationship",
            "emergency_contact_phone",
        )
        widgets = deepcopy(BASE_DISCLAIMER_FORM_WIDGETS)

accounts/templates/accounts/cookie_policy.html
{% extends "website/_base.html" %}
{% load static %}

{% block content %}

<div class="container-fluid">

    <h1 class="page-header">Cookie Policy</h1>
    <h4>Version: {{ cookie_policy.version }}.  Issue date: {{ cookie_policy.issue_date | date:'d M Y' }}.</h4>

    <p>
        {{ cookie_policy.content | linebreaks | safe }}
    </p>


    <p>For further information, please contact
        <a href="mailto:{{ studio_email }}">{{ studio_email }}</a>.</p>

    <p>View our full data privacy policy <a href="{% url 'data_privacy_policy' %}">here.</a></p>


</div>

{% endblock content %}

accounts/templates/accounts/data_privacy_policy.html
{% extends "website/_base.html" %}
{% load static %}

{% block title %}{% include "website/includes/header.html" with title="Data Privacy & Cookies Policy" %}{% endblock %}


{% block content %}

<div class="container mt-20">
    <div class="row">

    <h1 class="page-header">Data Privacy Policy</h1>
    <h4>Version: {{ data_privacy_policy.version }}.  Issue date: {{ data_privacy_policy.issue_date | date:'d M Y' }}.</h4>

    <p>
        {{ data_privacy_policy.content | linebreaks | safe }}
    </p>

    <h1>Cookie Policy</h1>
    <h4>Version: {{ cookie_policy.version }}.  Issue date: {{ cookie_policy.issue_date | date:'d M Y' }}.</h4>
    <p>
        {{ cookie_policy.content | linebreaks | safe }}
    </p>

    <p>For further information, please contact
        <a href="mailto:{{ studio_email }}">{{ studio_email }}</a></p>
    </div>

</div>
{% endblock content %}

accounts/templates/accounts/data_privacy_review.html
{% extends "website/_base.html" %}
{% load static %}

{% block title %}{% include "website/includes/header.html" with title="Data Privacy Policy" %}{% endblock %}


{% block content %}

<section>
    <div class="container mt-20">

        <div class="row">

            <p>Please review our {% if update_needed %}updated {% endif %}data privacy policy before proceeding.</p>

            {% if form.errors %}<div class="form-error">Please correct the errors below.{% endif %}</div>

            <form action="" method="post">{% csrf_token %}
                <div class="dp-box">
                <h4>Version: {{ form.data_privacy_policy.version }}.  Issue date: {{ form.data_privacy_policy.issue_date | date:'d M Y' }}.</h4>
                <p>
                    {{ form.data_privacy_policy.content | linebreaks | safe }}
                </p>

                </div>
                <div class="form-group">
                <div class="col-12 vspace {% if form.confirm.errors %}ticket-error{% endif %}">
                    {{ form.confirm }}<label for='id_confirm'></label>
                        <label class="control-label" for='id_confirm'>{{ form.confirm.label }}</label>
                        {% if form.confirm.errors %} {{ form.confirm.errors }}{% endif %}
                </div>
                <div class="studioadmin-help col-10 col-offset-2">{{ form.confirm.help_text }}</div>
            </div>

                <input type="hidden" name="next_url" value={{ form.next_url }}/>
                <input class="btn btn-color-01 tra-01-hover" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</section>
{% endblock content %}

accounts/templates/accounts/disclaimer_form.html
{% extends 'website/_base.html' %}
{% load static accounttags %}

{% block title %}
    {% if updating %}
        {% include "website/includes/header.html" with title="Updating Disclaimer" %}
    {% else %}
        {% include "website/includes/header.html" with title="Disclaimer" %}
    {% endif %}
{% endblock %}


{% block content %}
<div class="container mt-20">
    <div class="panel panel-transparent">
    <div class="panel-body">

    <h2>Disclaimer Form for {{ user.first_name }} {{ user.last_name }}</h2>
   {% if disclaimer and not updating %}
            <p>You have already completed a disclaimer.</p>

           <p>If you have any additional questions or concerns about the data you have provided, please contact <a href="mailto:{{ studio_email }}">{{ studio_email }}</a>.</p>
    {% else %}
        {% if updating %}
            <p>Previously completed on {% if form.instance.date_updated %}{{ form.instance.date_updated|date:'d M Y' }}{% else %}{{ form.instance.date|date:'d M Y' }}{% endif %}</p>
        {% endif %}
       {% include 'accounts/disclaimer_form_content.html' %}
           <p>If you have any additional questions or concerns, please contact <a href="mailto:{{ studio_email }}">{{ studio_email }}</a>.</p>

    {% endif %}
       <p>View our <a href="{% url 'data_privacy_policy' %}">data privacy policy.</a></p>
    </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/disclaimer_form_content.html
{% load django_bootstrap5 static crispy_forms_tags %}

{% block extrahead %}
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha512-f0tzWhCwVFS3WeYaofoLWkTP62ObhewQ1EZn65oSYDZUg1+CyywGKkWzm8BxaJj5HGKI72PnMH9jYyIFz+GH7g==" crossorigin="anonymous" />
{% endblock %}

{% if form.errors %}
    <div class="errorlist">Please correct the errors below</div>
    {{ form.non_form_errors }}
{% endif %}

   <form class="dirty-check" action="" method="post">
       {% csrf_token %}
        {% crispy form %}
   </form>


{% block extrascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha512-AIOTidJAcHBH2G/oZv9viEGXRqDNmfdPVPYOYKGy3fti0xIplnlgMHUGfuNRzC6FkzIo0iIxgFnr9RikFxK+sw==" crossorigin="anonymous"></script>
    <script src="{% static 'accounts/datetimepickers.js' %}"></script>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'website/_base.html' %}
{% load accounttags %}

{% block title %}{% include "website/includes/header.html" with title="Your Profile" %}{% endblock %}


{% block content %}

<section>

    <div class="container mt-20">
        <div class="card">
            <h2 class="card-header">Personal Details</h2>
            <div class="card-body">
                <div class="card-text"><strong>Username:</strong> {{ user.username }}</div>
                <div class="card-text"><strong>Name:</strong> {{ user.first_name }} {{ user.last_name }}</div>
                <div class="card-text"><a class="btn btn-sunshine tra-sunshine-hover btn-sm" href="{% url 'accounts:update_profile' %}">Change</a></div>

                </div>
            </div>
            <div class="card">
            <h2 class="card-header">Your Info and Emergency Contact Information</h2>
            <p>Your emergency contact will be contacted in the case of an accident or emergency.</p>
            <div class="card-body">
            <div class="card-text"><strong>Date of birth:</strong> {{ latest_disclaimer.date_of_birth }}</div>
            <div class="card-text"><strong>Contact phone number:</strong> {{ latest_disclaimer.phone }} </div>
            <div class="card-text"><strong>Emergency Contact Name:</strong> {{ latest_disclaimer.emergency_contact_name }} </div>
            <div class="card-text"><strong>Emergency Contact Phone:</strong> {{ latest_disclaimer.emergency_contact_phone }} </div>
            <div class="card-text"><strong>Relationship:</strong> {{ latest_disclaimer.emergency_contact_relationship }} </div>
            <div class="card-text"><a class="btn btn-sunshine tra-sunshine-hover btn-sm" href="{% url 'accounts:update_emergency_contact' user.id %}">Change</a></div>
            </div>
        </div>
        <div class="card">
        <h2 class="card-header">Email Addresses</h2>
        <div class="card-body">
            <div class="card-text"><strong>Primary email address:</strong> {{ user.email }}</div>
        <div class="card-text"><a class="btn btn-sm btn-sunshine tra-sunshine-hover" href="{% url 'account_email' %}">Change</a></div>
        </div>
        </div>
        <div class="card">
            <h2 class="card-header">Disclaimer</h2>
            <div class="card-body">
                <p>All students must have a completed and current disclaimer before any bookings can be made.  Disclaimers will need to be reviewed
                    annually and whenever terms are updated.</p>
                {% if user|has_disclaimer %}
                    <span class="badge rounded-pill badge-sunshine white-color">Completed</span>
                    <a href="{% url 'accounts:disclaimer_form_update' user.id %}"> View/update</a>
                {% else %}<span class="badge rounded-pill badge-dark">{% if user|has_expired_disclaimer %}Expired{% else %}Not Completed{% endif %}</span>
                    <a class="btn btn-sunshine tra-sunshine-hover btn-sm" href="{% url 'accounts:disclaimer_form' user.id %}"> Add new disclaimer</a>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}

accounts/templates/accounts/update_emergency_contact.html
{% extends 'website/_base.html' %}
{% load accounttags %}

{% load crispy_forms_tags %}

{% block title %}
    {% include "website/includes/header.html" with title="Edit Your Contact Information" %}
{% endblock %}

{% block content %}

<section>

    <div class="container mt-20">

        <p>Your emergency contact will be contacted in the case of an accident or emergency.</p>

        {% if form.errors %}
            <div class="errorlist">Please correct the errors below</div>
        {% endif %}

        <form class="dirty-check form" action="" method="post">
            {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/update_profile.html
{% extends 'website/_base.html' %}
{% load static %}

{% block title %}
    {% include "website/includes/header.html" with title="Edit Your Account Profile" %}
{% endblock %}

{% block content %}

<section>

    <div class="container mt-20">

        <form action="" method="post">{% csrf_token %}
            {% csrf_token %}
                {{ form.non_field_errors }}
                    {% for field in form %}
                        {% if field.name == 'confirmation_key' %}
                            <span class="d-none">{{ field }}</span>
                        {% else %}
                            <div class="form-group">
                                <label class="control-label" for="{{ field.name }}_id">{{ field.label }}{% if field.field.required %}*{% endif %}</label><br/>
                                <div class="{% if form.field.errors %}errorlist{% endif %}">{{ field }}</div>
                                <div class="helptext">{{ field.help_text }}</div>
                                {% if field.errors %}
                                    <div class="errorlist">
                                        {{ field.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
            <div class="mt-10">
                <input class="btn btn-green tra-green-hover" type="submit" value="Update" />
                <a href="{% url 'accounts:profile' %}"><div class="btn btn-color-01 tra-01-hover">Cancel</div></a>
            </div>
        </form>
    </div>

</section>
{% endblock content %}