accounts/urls.py
from django.urls import path

from .views import (
    profile,
    ProfileUpdateView,
    SignedDataPrivacyCreateView,
    DisclaimerCreateView,
    DisclaimerUpdateView,
    DisclaimerContactUpdateView,
)

app_name = "accounts"


urlpatterns = [
    path("profile/", profile, name="profile"),
    path("update/", ProfileUpdateView.as_view(), name="update_profile"),
    path(
        "data-privacy-review/",
        SignedDataPrivacyCreateView.as_view(),
        name="data_privacy_review",
    ),
    path(
        "disclaimer/<int:user_id>/update",
        DisclaimerUpdateView.as_view(),
        name="disclaimer_form_update",
    ),
    path(
        "disclaimer/<int:user_id>/",
        DisclaimerCreateView.as_view(),
        name="disclaimer_form",
    ),
    path(
        "emergency-contact/<int:user_id>/update/",
        DisclaimerContactUpdateView.as_view(),
        name="update_emergency_contact",
    ),
    path("", profile),
]

booking/urls.py
from django.urls import path
from django.views.generic import RedirectView


from booking.views import (
    RegularClassesEventListView,
    WorkshopEventListView,
    EventDetailView,
    PrivateClassesEventListView,
    BookingListView,
    BookingHistoryListView,
    toggle_waiting_list,
    shopping_basket_view,
    guest_shopping_basket,
    stripe_checkout,
    ajax_cart_item_delete,
    check_total,
    ajax_add_membership_to_basket,
    membership_purchase_view,
    MembershipListView,
    MembershipDetailView,
    GiftVoucherUpdateView,
    GiftVoucherPurchaseView,
    GiftVoucherDetailView,
    voucher_details,
    toggle_booking,
)
from booking.views.user_invoices_views import UserInvoiceListView


app_name = "booking"


urlpatterns = [
    path("my-bookings/", BookingListView.as_view(), name="bookings"),
    path("my-memberships/", MembershipListView.as_view(), name="user_memberships"),
    path(
        "membership-detail/<int:pk>/",
        MembershipDetailView.as_view(),
        name="membership_detail",
    ),
    path("booking-history/", BookingHistoryListView.as_view(), name="booking_history"),
    path(
        "classes/", RegularClassesEventListView.as_view(), name="regular_session_list"
    ),
    path("privates/", PrivateClassesEventListView.as_view(), name="private_list"),
    path("workshops/", WorkshopEventListView.as_view(), name="workshop_list"),
    path("event/<slug:slug>/", EventDetailView.as_view(), name="event_detail"),
    path("toggle-booking/<int:event_id>/", toggle_booking, name="toggle_booking"),
    path(
        "toggle-waiting-list/<int:event_id>/",
        toggle_waiting_list,
        name="toggle_waiting_list",
    ),
    # GIFT VOUCHERS
    path("gift-vouchers/", GiftVoucherPurchaseView.as_view(), name="buy_gift_voucher"),
    path(
        "gift-vouchers/<slug:slug>/update",
        GiftVoucherUpdateView.as_view(),
        name="gift_voucher_update",
    ),
    path(
        "gift-vouchers/<slug:slug>",
        GiftVoucherDetailView.as_view(),
        name="gift_voucher_details",
    ),
    path("voucher/<str:voucher_code>", voucher_details, name="voucher_details"),
    # MEMBERSHIPS
    path("memberships/", membership_purchase_view, name="membership_purchase"),
    path(
        "ajax-membership-purchase/",
        ajax_add_membership_to_basket,
        name="ajax_add_membership_to_basket",
    ),
    # SHOPPING BASKET
    path("shopping-basket/", shopping_basket_view, name="shopping_basket"),
    path("stripe-checkout/", stripe_checkout, name="stripe_checkout"),
    path("ajax-cart-item-delete/", ajax_cart_item_delete, name="ajax_cart_item_delete"),
    path("check-total/", check_total, name="check_total"),
    path("guest-shopping-basket/", guest_shopping_basket, name="guest_shopping_basket"),
    # transactions
    path("payment-history/", UserInvoiceListView.as_view(), name="transactions"),
    path("", RedirectView.as_view(url="/classes/", permanent=True)),
]

sunshine/urls.py
from django.urls import include, path, re_path

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import (
    CustomLoginView,
    CustomSignUpView,
    data_privacy_policy,
    cookie_policy,
)
from booking.views import permission_denied
from studioadmin.views.views import redirect_to_admin

urlpatterns = [
    path("", include("website.urls")),
    path("accounts/signup/", CustomSignUpView.as_view(), name="account_signup"),
    path("accounts/login/", CustomLoginView.as_view(), name="account_login"),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("data-privacy-policy/", data_privacy_policy, name="data_privacy_policy"),
    path("cookie-policy/", cookie_policy, name="cookie_policy"),
    re_path(r"^pf_admin.*", redirect_to_admin, name="redirect_old_link"),
    path("instructor-admin/", include("studioadmin.urls")),
    path("site-admin/", admin.site.urls),
    path("booking/", include("booking.urls")),
    path("timetable/", include("timetable.urls")),
    path("payments/", include("stripe_payments.urls")),
    path("not-available/", permission_denied, name="permission_denied"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:  # pragma: no cover
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

admin.autodiscover()
admin.site.site_header = "Sunshine Fitness"
admin.site.enable_nav_sidebar = False

booking/views/ajax_views.py
import json

from urllib.parse import parse_qs, urlsplit, urlunsplit, urlencode

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest, JsonResponse, HttpResponse
from django.template.response import TemplateResponse
from django.views.decorators.http import require_http_methods
from django.urls import reverse
from django.shortcuts import get_object_or_404


from activitylog.models import ActivityLog
from booking.views.views_utils import (
    get_unpaid_bookings,
    get_unpaid_memberships,
    get_unpaid_gift_vouchers,
    get_unpaid_gift_vouchers_from_session,
    total_unpaid_item_count,
)
from .booking_helpers import cancel_booking_from_view
from booking.models import Event, Booking, GiftVoucher, Membership, WaitingListUser
from booking.email_helpers import send_email, email_waiting_lists
from booking.utils import calculate_user_cart_total, host_from_request


ITEM_TYPE_MODEL_MAPPING = {
    "membership": Membership,
    "booking": Booking,
    "gift_voucher": GiftVoucher,
}


@login_required
def toggle_waiting_list(request, event_id):
    user = request.user
    event = get_object_or_404(Event, pk=event_id)
    ev_type = "class" if event.event_type != "workshop" else event.event_type
    tab = request.POST.get("tab")
    ref = request.POST.get("ref", "event")
    booking_id = request.POST.get("booking_id")

    if booking_id:
        booking = request.user.bookings.get(id=int(booking_id))
    else:
        booking = None

    if request.user.has_outstanding_fees():
        message = (
            "Action forbidden until outstanding cancellation fees have been resolved"
        )
        return HttpResponseBadRequest(message)

    # toggle current status
    try:
        waitinglistuser = WaitingListUser.objects.get(user=user, event=event)
        waitinglistuser.delete()
    except WaitingListUser.DoesNotExist:
        WaitingListUser.objects.create(user=user, event=event)

    headers = _get_redirect_headers(request, tab)
    context = {"event": event, "type": ev_type, "booking": booking}
    return TemplateResponse(
        request, f"booking/includes/{ref}_row.html", context, headers=headers
    )


@require_http_methods(["POST"])
def ajax_cart_item_delete(request):
    item_type = request.POST.get("item_type")
    item_id = request.POST.get("item_id")
    item = get_object_or_404(ITEM_TYPE_MODEL_MAPPING[item_type], pk=item_id)
    if item_type == "booking":
        event = item.event

    unpaid_items = {"booking": [], "membership": [], "gift_voucher": []}
    if request.user.is_authenticated:
        item.delete()
        unpaid_items["membership"] = get_unpaid_memberships(request.user)
        unpaid_items["booking"] = get_unpaid_bookings(request.user)
        unpaid_items["gift_voucher"] = get_unpaid_gift_vouchers(request.user)
        total = calculate_user_cart_total(
            unpaid_items["membership"],
            unpaid_items["booking"],
            unpaid_items["gift_voucher"],
        )
        unpaid_item_count = total_unpaid_item_count(request.user)
    else:
        assert item_type == "gift_voucher"
        gift_vouchers_on_session = request.session.get("purchases", {}).get(
            "gift_vouchers", []
        )
        if int(item_id) in gift_vouchers_on_session:
            gift_vouchers_on_session.remove(int(item_id))
            request.session["purchases"]["gift_vouchers"] = gift_vouchers_on_session
            item.delete()
        unpaid_items["gift_voucher"] = get_unpaid_gift_vouchers_from_session(request)
        unpaid_item_count = unpaid_items["gift_voucher"].count()
        total = calculate_user_cart_total(
            unpaid_gift_vouchers=unpaid_items["gift_voucher"]
        )
    if item_type == "booking":
        # send waiting list emails if necessary
        email_waiting_lists([event.id], host=host_from_request(request))

    if not unpaid_items[item_type]:
        return JsonResponse(
            {
                "redirect": True,
                "url": reverse("booking:shopping_basket"),
            }
        )

    return JsonResponse(
        {
            "cart_total": total,
            "cart_item_menu_count": unpaid_item_count,
        }
    )


@login_required
@require_http_methods(["POST"])
def toggle_booking(request, event_id):
    event = get_object_or_404(Event, pk=event_id)

    ev_type = "class" if event.event_type != "workshop" else event.event_type

    context = {"event": event, "type": ev_type}

    existing_booking_status = None
    booking_id = request.POST.get("booking_id")
    tab = request.POST.get("tab")
    ref = request.POST.get("ref", "event")
    if booking_id:
        booking = request.user.bookings.get(id=int(booking_id))
        if booking.status == "CANCELLED" or booking.no_show:
            existing_booking_status = "CANCELLED"
        else:
            existing_booking_status = "OPEN"

    # if making a new/reopening booking, make sure the event isn't full or cancelled
    # and abort if user has outstanding fees
    if existing_booking_status != "OPEN":  # i.e. None (new) or CANCELLED (reopening)
        if request.user.has_outstanding_fees():
            message = "Action forbidden until outstanding cancellation fees have been resolved"
            return HttpResponseBadRequest(message)

        if not event.spaces_left or event.cancelled:
            message = "Sorry, this {} {}".format(
                ev_type,
                "is now full" if not event.spaces_left else "has been cancelled",
            )
            return HttpResponseBadRequest(message)

    if existing_booking_status == "OPEN" and not booking.paid:
        # booking already open and unpaid; user clicked on go-to-basket button
        url = reverse("booking:shopping_basket")
        return HttpResponse("", headers={"Hx-Redirect": url})

    if existing_booking_status is None:
        booking = Booking.objects.create(user=request.user, event=event)
    new = existing_booking_status is None

    context["booking"] = booking

    alert_message = {}
    # CANCELLING
    if existing_booking_status == "OPEN":
        # cancel, process refunds etc, email users, email waiting list
        alert_message = cancel_booking_from_view(request, booking)
        action = "cancelled"

    # REOPENING
    elif existing_booking_status == "CANCELLED":
        booking.status = "OPEN"
        booking.no_show = False
        action = "reopened"

    # NEW BOOKING
    elif new:
        booking.status = "OPEN"
        booking.no_show = False
        action = "created"

    if action in ["reopened", "created"]:
        # assign membership if available
        available_user_membership = booking.event.get_available_user_membership(
            booking.user
        )
        if available_user_membership:
            booking.membership = available_user_membership
            booking.paid = True

    booking.save()

    if action != "cancelled" and booking.paid:
        # ONLY SEND EMAILS IF BOOKING IS PAID (i.e. fully booked with membership)
        # Otherwise emails are sent after payment made
        ActivityLog.objects.create(
            log=f'Booking {booking.id} {action} for "{booking.event}" by user {booking.user.username}'
        )
        # send email to user
        ctx = {
            "booking": booking,
            "event": booking.event,
            "date": booking.event.date.strftime("%A %d %B"),
            "time": booking.event.date.strftime("%H:%M"),
            "ev_type": ev_type,
        }

        text_template, html_template = (
            "booking/email/booking_received.txt",
            "booking/email/booking_received.html",
        )
        send_email(
            request,
            "Booking {} for {}".format(action, event.name),
            ctx,
            text_template,
            html_template,
            to_list=[booking.user.email],
        )

        # send email to studio if flagged for the event
        if booking.event.email_studio_when_booked:
            send_email(
                request,
                "{} {} has just booked for {}".format(
                    booking.user.first_name, booking.user.last_name, booking.event
                ),
                ctx,
                "booking/email/to_studio_booking.txt",
                to_list=[settings.DEFAULT_STUDIO_EMAIL],
            )

    # messages for opened/reopened (cancel messages already generated)
    if action in ["created", "reopened"]:
        context["is_booked"] = True
        alert_message["level"] = "success"
        if booking.paid:
            alert_message["message"] = "Booked."
        else:
            alert_message["message"] = "Added to basket."

    context["cart_item_count"] = total_unpaid_item_count(request.user)

    # remove from waiting list if necessary
    try:
        waiting_list_user = WaitingListUser.objects.get(user=request.user, event=event)
        if action in ["created", "reopened"]:
            waiting_list_user.delete()
            ActivityLog.objects.create(
                log="User {} removed from waiting list for {}".format(
                    request.user.username, event
                )
            )
    except WaitingListUser.DoesNotExist:
        pass

    headers = _get_redirect_headers(request, tab)

    if alert_message:
        headers["Hx-Trigger"] = json.dumps(
            {
                "showAlert": {
                    "level": alert_message["level"],
                    "message": alert_message["message"],
                    "title": str(event),
                }
            }
        )

    return TemplateResponse(
        request, f"booking/includes/{ref}_row.html", context, headers=headers
    )


def _get_redirect_headers(request, tab):
    headers = {}
    tab = int(tab) if tab else 0
    # redirect if tab is not 0 or user now has fees outstanding
    if (tab != 0) or request.user.has_outstanding_fees():

booking/views/booking_views.py
# -*- coding: utf-8 -*-
import logging

from django.views.generic import ListView
from django.utils import timezone
from braces.views import LoginRequiredMixin
from booking.email_helpers import email_waiting_lists

from booking.models import Booking
from booking.utils import host_from_request
from .views_utils import DataPolicyAgreementRequiredMixin


logger = logging.getLogger(__name__)


class BookingListView(DataPolicyAgreementRequiredMixin, LoginRequiredMixin, ListView):
    model = Booking
    context_object_name = "bookings"
    template_name = "booking/bookings.html"
    paginate_by = 20

    def dispatch(self, request, *args, **kwargs):
        # Cleanup bookings so user is looking at current availability
        event_ids_from_expired_bookings = Booking.cleanup_expired_bookings(
            use_cache=True
        )
        email_waiting_lists(
            event_ids_from_expired_bookings, host=host_from_request(request)
        )
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Booking.objects.filter(
            event__date__gte=timezone.now(), user=self.request.user
        ).order_by("event__date")

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["section"] = "account"
        context["title"] = "Bookings"

        return context


class BookingHistoryListView(
    DataPolicyAgreementRequiredMixin, LoginRequiredMixin, ListView
):
    model = Booking
    context_object_name = "bookings"
    template_name = "booking/bookings.html"
    paginate_by = 20

    def get_queryset(self):
        return Booking.objects.filter(
            event__date__lte=timezone.now(), user=self.request.user
        ).order_by("-event__date")

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the history flag
        context["history"] = True
        context["section"] = "account"
        context["title"] = "Past Bookings"

        return context

booking/templates/booking/includes/add_membership_button.html
<div class="btn btn-xs btn-sunshine tra-sunshine-hover">
    <i id="loader_{{ option.membership_type.id }}_{{ option.month }}_{{ option.year }}">
    <span class="pr-1"></i>Add <i class="fas fa-shopping-cart"></i>
        {% if option.basket_count > 0 %}({{ option.basket_count }}){% endif %}
     </span>
</div>

booking/templates/booking/includes/ajax_head.html
{% load static %}
<link rel="stylesheet" href="{% static 'booking/vanilla-notify.css' %}">
<script type='text/javascript' src="{% static 'booking/vanilla-notify.min.js' %}"></script>
<script type="text/javascript">window.CSRF_TOKEN = "{{ csrf_token }}";</script>

booking/templates/booking/includes/book_button.html
{% if button_data.members_only_not_allowed %}
    <span class="btn btn-sunshine tra-sunshine-hover book_button disabled" disabled=disabled>Members only</span>
{% else %}
    {% comment %} booking button {% endcomment %}
    <span 
        hx-post={% url 'booking:toggle_booking' button_data.event.id %}
        hx-trigger="click"
        hx-target="#table-row-event-{{ button_data.event.id }}"
        hx-vals='{"booking_id": "{{ booking.id }}", "tab": "{{ location.index }}", "ref": "{{ button_data.ref }}"}'
        hx-swap="outerHTML"
        {% if button_data.show_cancellation_warning %}hx-confirm="Cancelling at this time will incur a fee of £{{ event.cancellation_fee }}. Are you sure you wish to cancel?"{% endif %}   
    >
        {% if button_data.can_go_to_basket %}
            <span class="btn btn-xs book-btn btn-oak tra-oak-hover">
                View basket <i class="fa fa-shopping-basket"></i>
            </span>
        {% elif button_data.can_cancel %}
            <span class="btn btn-xs book-btn btn-pink tra-pink-hover">Cancel</span>
        {% elif button_data.can_rebook %}
            <span class="btn btn-xs book-btn btn-green tra-green-hover">Rebook</span>
        {% elif button_data.can_book %}
            <span class="btn btn-xs book-btn btn-green tra-green-hover">Book</span>
        {% elif button_data.can_add_to_basket %}
            <span class="btn btn-xs book-btn btn-sunshine tra-sunshine-hover">Add to basket</span>
        {% endif %}
    </span>
{% endif %}

booking/templates/booking/includes/booking_row.html
{% load accounttags bookingtags static %}

{% if request.htmx %}
    <span id="cart_item_menu_count_xs" hx-swap-oob="true">{{cart_item_count}}</div>
    <span id="cart_item_menu_count" hx-swap-oob="true">{{cart_item_count }}</span>
{% endif %}

{% book_button_data booking.event user booking "booking" as button_data %}

<li
    id="table-row-event-{{ booking.event.id }}"
    class="list-group-item 
        {% if not button_data.can_cancel %}
            expired
        {% endif %}">
    <div class="row">
    {% if not history %}
        <div class="col">
            {% if booking.event.cancelled %}
                <span class="btn btn-xs book-btn text-secondary disabled">CANCELLED</span>
            {% elif user.has_outstanding_fees %}
                {% include "booking/includes/outstanding_fee_disabled_buttons.html" %}
            {% elif button_data.show_book_button %}
                {% include 'booking/includes/book_button.html' %}
            {% else %}
                {% include "booking/includes/waiting_list_toggle.html" %}
            {% endif %}
            </div>
    {% endif %}
    <div class="col">{{ booking.event.date | date:"H:i" }}</div>
    <div class="col">
        <a href="{% url 'booking:event_detail' booking.event.slug %}">
            {{ booking.event.name }}
        </a>
    </div>
    <div class="col">{{ booking.event.venue.abbreviation }}</div>
    <div class="col">{% if button_data.can_cancel %}OPEN{% else %}CANCELLED{% endif %}</div>
    <div class="col">
        {% if not booking.event.cancelled %}
            Paid:
            {% if booking.paid %}
                {% if booking.membership %}
                    <a href={% url "booking:membership_detail" booking.membership.id %}>
                        <img src={% static 'booking/images/circle-m.svg' %} />
                    </a>
                {% else %}
                    <span class="text-success fas fa-check-circle"/></span>
                {% endif %}
            {% else %}
                <span class="text-danger fas fa-times-circle"/></span>
            {% endif %}
        {% endif %}
    </div>
</div>
</li>

booking/templates/booking/includes/event_row.html
{% load accounttags bookingtags %}

{% if request.htmx %}
    <span id="cart_item_menu_count_xs" hx-swap-oob="true">{{cart_item_count}}</div>
    <span id="cart_item_menu_count" hx-swap-oob="true">{{cart_item_count }}</span>
{% endif %}

{% book_button_data event user booking "event" as button_data %}

<li
    id="table-row-event-{{ event.id }}"
    class="list-group-item 
        {% if event.cancelled %}
            expired
        {% elif button_data.is_booked %}
            {% if booking.paid %}list-group-item-success{% else %}list-group-item-warning{% endif %}
        {% endif %}">
    <div class="row">
    {% if user.is_authenticated %}
        {% if event.id in staff_only_events %}
            <div class="col-sm col-12">VISIBLE TO STAFF ONLY</div>
        {% else %}
            <div class="col-sm col-12">
                {% if user|has_disclaimer %}
                    {% if event.cancelled %}
                        <span class="btn btn-xs book-btn text-secondary disabled">CANCELLED</span>
                    {% elif user.has_outstanding_fees %}
                        {% include "booking/includes/outstanding_fee_disabled_buttons.html" %}
                    {% elif button_data.show_book_button %}
                        {% include 'booking/includes/book_button.html' %}
                    {% else %}
                        {% include "booking/includes/waiting_list_toggle.html" %}
                    {% endif %}
                {% else %}
                <em><a href="{% url 'accounts:disclaimer_form' user.id %}">Complete disclaimer</a></em>
                {% endif %}
                    </div>
        {% endif %}
    {% else %}
        <div class="col-sm col-12">
            <a class='btn btn-sunshine tra-sunshine-hover' href="{% url 'account_login' %}?next={{request.get_full_path|urlencode }}">Log&nbsp;in to&nbsp;book</a>
        </div>
    {% endif %}
    <div class="col">{{ event.date | date:"H:i" }}</div>
    <div class="col"><a href="{% url 'booking:event_detail' event.slug %}">
        {% if booking and booking.paid and booking.status == "OPEN" and not booking.no_show %}
         <i class="fas fa-check-circle text-success"></i>
        {% endif %}
        {{ event.name }}</a>
    </div>
    <div class="col">{{ event.venue.abbreviation }}</div>
    <div class="col offset-6 col-2">£{{ event.cost }}</div>
    <div class="col-sm col-3 me-auto">
        {% if event.max_participants %}
            {% if not event.cancelled %}
            <span id="booking_count_{{ event.id }}"
                class="badge rounded-pill {% if event.spaces_left == 0 %}badge-dark{% else %}badge-green{% endif%}">
                {{ event.spaces_left }}/{{ event.max_participants }}
            </span>
            {% endif %}
        {% else %}N/A{% endif %}
    </div>
</div>
</li>

booking/templates/booking/includes/events_pagination.html
{% load bookingtags %}

{% if page_obj.paginator.num_pages > 1 %}
<div class="pagination">
    <span class="page-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}&tab={{ tab }}{% if request.GET.name %}&name={{ request.GET.name }}{% endif %}{% if request.GET.type %}&type={{ request.GET.type }}{% endif %}">
                Previous</a>
        {% else %}
            <a class="disabled" disabled=disabled href="#">Previous</a>
        {% endif %}
        --
        {% for i in page_obj.paginator.num_pages|get_range:1 %}
            {% if i != page_obj.number %}
                <a href="?page={{ i }}&tab={{ tab }}{% if request.GET.name %}&name={{ request.GET.name }}{% endif %}{% if request.GET.type %}&type={{ request.GET.type }}{% endif %}">
                    {{ i }}</a>
        {% else %}<span class="current-page">{{ i }}</span>
            {% endif %}
        {% endfor %}
        --
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&tab={{ tab }}{% if request.GET.name %}&name={{ request.GET.name }}{% endif %}{% if request.GET.type %}&type={{ request.GET.type }}{% endif %}">
                Next</a>
        {% else %}
            <a class="disabled" href="#">Next</a>
        {% endif %}
    </span>
</div>
{% endif %}

booking/templates/booking/includes/fees_due_banner.html
{% if user.is_authenticated and user.has_outstanding_fees %}
  <div id="message-row"  class="row">
    <div class="col-12">
        <div class="message alert alert-outstanding-fees">
            <i class="fas fa-ban fa-2x"></i>
            Your account is locked for booking due to outstanding fees.  You can still cancel existing bookings.<br/>
            Please contact the studio to unlock your account.
            <i class="fas fa-ban"></i>
        </div>
    </div>
  </div>
{% endif %}

booking/templates/booking/includes/outstanding_fee_disabled_buttons.html
{% if button_data.show_book_button %}
    <span class="btn book-btn btn-xs btn-sunshine tra-sunshine-hover disabled" id="book_button_disabled">
        {% if button_data.can_go_to_basket %}
            View basket
        {% elif button_data.can_cancel %}
            Cancel
        {% elif button_data.can_rebook %}
            Rebook
        {% elif button_data.can_book %}
            Book
        {% elif button_data.can_add_to_basket %}
            Add to basket
        {% endif %}
    </span>
{% elif button_data.on_waiting_list  %}
    <button class="btn book-btn btn-xs btn-sunshine tra-sunshine-hover disabled" id="leave_waiting_list_button_disabled">Leave waiting list</button>
{% else %}
    <button class="btn book-btn btn-xs btn-sunshine tra-sunshine-hover disabled" id="join_waiting_list_button_disabled">Join waiting list</button>
{% endif %}

booking/templates/booking/includes/pagination.html
{% load bookingtags %}

{% if page_obj.paginator.num_pages > 1 %}
<div class="pagination">
    <span class="page-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% else %}
            <a class="disabled" disabled=disabled href="#">Previous</a>
        {% endif %}
        --
        {% for i in paginator.num_pages|get_range:1 %}
            {% if i != page_obj.number %}
                <a href="?page={{ i }}">{{ i }}</a>
        {% else %}<span class="current-page">{{ i }}</span>
            {% endif %}
        {% endfor %}
        --
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
        {% else %}
            <a class="disabled" href="#">Next</a>
        {% endif %}
    </span>
</div>
{% endif %}

booking/templates/booking/includes/waiting_list_toggle.html
<span 
hx-post={% url 'booking:toggle_waiting_list' button_data.event.id %}
hx-trigger="click"
hx-target="#table-row-event-{{ button_data.event.id }}"
hx-vals='{"booking_id": "{{ booking.id }}", "tab": "{{ location.index }}", "ref": "{{ button_data.ref }}"}'
hx-swap="outerHTML"
>
    {% if button_data.on_waiting_list %}
        <button class="btn btn-tra-01 color-01-hover btn-xs book-btn" id="leave_waiting_list_button">Leave waiting list</button>
    {% else %}
        <button class="btn btn-color-01 tra-01-hover btn-xs book-btn" id="join_waiting_list_button">Join waiting list</button>
    {% endif %}
</span>